USE [master]
GO

/****** Object:  Database [Accounting_DB]    Script Date: 7/19/2025 1:38:07 PM ******/
CREATE DATABASE [Accounting_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Accounting_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Accounting_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Acc2Test_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Acc2Test_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Accounting_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Accounting_DB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Accounting_DB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Accounting_DB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Accounting_DB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Accounting_DB] SET ARITHABORT OFF 
GO

ALTER DATABASE [Accounting_DB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Accounting_DB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Accounting_DB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Accounting_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Accounting_DB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Accounting_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Accounting_DB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Accounting_DB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Accounting_DB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Accounting_DB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Accounting_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Accounting_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Accounting_DB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Accounting_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Accounting_DB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Accounting_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Accounting_DB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Accounting_DB] SET RECOVERY FULL 
GO

ALTER DATABASE [Accounting_DB] SET  MULTI_USER 
GO

ALTER DATABASE [Accounting_DB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Accounting_DB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Accounting_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Accounting_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Accounting_DB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Accounting_DB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Accounting_DB] SET  READ_WRITE 
GO


USE [Accounting_DB]
GO

/****** Object:  Table [dbo].[Customers]    Script Date: 7/19/2025 1:38:29 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Customers](
	[CustomerID] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](250) NOT NULL,
	[Mobile] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](150) NULL,
	[Address] [nvarchar](800) NULL,
	[CustomerImage] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [Accounting_DB]
GO

/****** Object:  Table [dbo].[AccountingType]    Script Date: 7/19/2025 1:39:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AccountingType](
	[TypeID] [int] NOT NULL,
	[TypeTitle] [nvarchar](150) NOT NULL,
 CONSTRAINT [PK_AccountingType] PRIMARY KEY CLUSTERED 
(
	[TypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [Accounting_DB]
GO

INSERT INTO AccountingType
           (TypeID
           ,TypeTitle)
     VALUES
           ('1','دریافتی')
INSERT INTO AccountingType
           (TypeID
           ,TypeTitle)
     VALUES
           ('2','پرداختی')
GO


/****** Object:  Table [dbo].[Accounting]    Script Date: 7/19/2025 1:39:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Accounting](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CustomerID] [int] NOT NULL,
	[TypeID] [int] NOT NULL,
	[Amount] [int] NOT NULL,
	[Description] [nvarchar](500) NULL,
	[DateTitle] [datetime] NOT NULL,
 CONSTRAINT [PK_Accounting] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Accounting]  WITH CHECK ADD  CONSTRAINT [FK_Accounting_AccountingType] FOREIGN KEY([TypeID])
REFERENCES [dbo].[AccountingType] ([TypeID])
GO

ALTER TABLE [dbo].[Accounting] CHECK CONSTRAINT [FK_Accounting_AccountingType]
GO

ALTER TABLE [dbo].[Accounting]  WITH CHECK ADD  CONSTRAINT [FK_Accounting_Customers] FOREIGN KEY([CustomerID])
REFERENCES [dbo].[Customers] ([CustomerID])
GO

ALTER TABLE [dbo].[Accounting] CHECK CONSTRAINT [FK_Accounting_Customers]
GO


USE [Accounting_DB]
GO

/****** Object:  Table [dbo].[Login]    Script Date: 7/19/2025 1:40:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Login](
	[LoginID] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [nvarchar](150) NOT NULL,
	[Password] [nvarchar](150) NOT NULL,
 CONSTRAINT [PK_Login] PRIMARY KEY CLUSTERED 
(
	[LoginID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [Accounting_DB]
GO

INSERT INTO Login
           (UserName
           ,Password)
     VALUES
           ('admin','admin')
GO


